version: '3'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: blogapp
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    ports:
      - "3306:3306"

  # Nginx service (optional)
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php
